### ISSUE TITLE
Web UX: Collection view scrolling

### ISSUE THREAD

**Issue by jaredbell** [gskinnerTeam/flutter-wonderous-app#140]
There is currently no obvious way to scroll the collection view on web, landscape when the scroll region goes horizontal.

Ideally, the mouse scroll wheel would still navigate this view even though it is horizontal because the scrollbars are hidden, and otherwise the view relies on click and drag.

![image](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/6a509a38-2dec-4bca-b9df-3b8c91596787)

**Comment by esDotDev** [comment]
@jaredbell Considering we've fixed #147 which turns scrollbars on permanently for web/desktop, do you think this still needs additional scrollwheel support?

**Comment by AlexGarneau** [comment]
The scroll bar is no longer hidden, but the mousewheel still does not affect the scrollability of the view. Will remedy.

**Comment by AlexGarneau** [comment]
Two fixes. I created a PR that allows the default mouse-wheel to scroll this view, but the view already lets the user hold shift and then mouse-wheel to navigate. Supposedly it's the conventional use case. Will need confirmation as to which fix to use.
